services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: analog-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongo:27017/analog_db?authSource=admin
    depends_on:
      - mongo
    networks:
      - app_network
    volumes:
      - .:/app
      - /app/node_modules
    # Hot reload is enabled by default with start:dev

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=analog_db
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local

